### ISSUE TITLE
GeoMock doesn't work it Firefox

### ISSUE THREAD

**Issue by nfedyashev** [janmonschke/GeoMock#1]
http://janmonschke.com/GeoMock/example.html - Example works great in webkit browsers but I can't make GeoMock work in Firefox.

It just shows a blank page, no warnings/errors.

Jan, do you know any way to make it work in Firefox?

If this is security feature of Firefox then maybe we can mention in README that GeoMock doesn't work in Firefox(Selenium love it)

**Comment by janmonschke** [comment]
I see, haven't tested it in Firefox. Apparently you can't override the geolocation object. Thx for mentioning!
