### ISSUE TITLE
waypoints must include accuracy by geolocation specification

### ISSUE THREAD

**Issue by nfedyashev** [janmonschke/GeoMock#2]
http://dev.w3.org/geo/api/spec-source.html#coordinates_interface

```
interface Coordinates {
  readonly attribute double latitude;
  readonly attribute double longitude;
  readonly attribute double? altitude;
  readonly attribute double accuracy;
  readonly attribute double? altitudeAccuracy;
  readonly attribute double? heading;
  readonly attribute double? speed;
};
```

`accuracy` is a mandatory field that has to be present along with `latitude` and `longitude` but currently it is missing.

@janmonschke Would you accept pull-request?

**Comment by janmonschke** [comment]
Of course I will accept pull requests :)
